language: csharp
mono: none
dotnet: 2.1.4
branches:
  except:
    - gh-pages
env:
  global:
    - GH_REPO_NAME: CodeGen
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/lnupmi11/CodeGen.git
addons:
  apt:
    packages:
      - doxygen
      - graphviz
install:
- dotnet restore
jobs:
  include:
    - stage: build
      script: 
        - dotnet build
    - stage: test
      script:
      - dotnet xunit
    - stage: docs
      if: branch IN (master, dev, creating-structure)
      script:
      - cd $TRAVIS_BUILD_DIR
      - ./deploy/generate_docs.sh
